### ISSUE TITLE
Could not load file or assembly 'LiteX Storage Core'

### ISSUE THREAD

**Issue by usama-azakaw** [a-patel/LiteXStorage#1]
Getting this at startup.cs services.AddLiteXAmazonBlobService();

Error:
": 'Could not load file or assembly 'LiteX Storage Core, Version=6.3.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'"

**Comment by a-patel** [comment]
@usama-azakaw 
Could you please share more details.
e.g. installed LiteX NuGet packages with version numbers.

**Comment by a-patel** [comment]
have you installed LiteX.Storage.Core package, @usama-azakaw ?

**Comment by usama-azakaw** [comment]
Yes I have installed
![image](https://user-images.githubusercontent.com/53209642/62271052-ac210180-b448-11e9-8b05-d5c7f268723b.png)

**Comment by usama-azakaw** [comment]
I'm running this in .net core 2.2 environment

**Comment by a-patel** [comment]
@usama-azakaw  Please try below configuration option.

`
            // 2. Load configuration settings using options.
            services.AddLiteXAmazonBlobService(option =>
            {
                option.AmazonAwsSecretAccessKey = "";
                option.AmazonAwsAccessKeyId = "";
                option.AmazonBucketName = "";
                option.AmazonRegion = "";
            });
            services.AddLiteXAmazonBlobService(amazonBlobConfig);

            //OR
            // 3. Load configuration settings on your own.
            // (e.g. appsettings, database, hardcoded)
            var amazonBlobConfig = new AmazonBlobConfig()
            {
                AmazonAwsSecretAccessKey = "",
                AmazonAwsAccessKeyId = "",
                AmazonBucketName = "",
                AmazonRegion = "",
            };
            services.AddLiteXAmazonBlobService(amazonBlobConfig);
`

**Comment by a-patel** [comment]
@usama-azakaw 

New version released with many new features [7.0.0 - Multiple Provider support](https://github.com/a-patel/LiteXStorage/releases/tag/7.0.0)

Please try now. Also, check the documentation for more details.
